version: "3.8"
services:
  FineManagement:
    container_name: FineManagement
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true
